pipeline {
    agent any
    environment {
        BACKEND_IMAGE = "backend-app:latest"
        FRONTEND_IMAGE = "frontend-app:latest"
    }
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/pdevanshu08/cicd-project.git'
            }
        }
        stage('Build Backend') {
            steps {
                sh '''
                cd backend
                docker build -t $BACKEND_IMAGE .
                '''
            }
        }
        stage('Build Frontend') {
            steps {
                sh '''
                cd frontend
                docker build -t $FRONTEND_IMAGE .
                '''
            }
        }
        stage('Stop Running Containers') {
            steps {
                sh '''
                docker-compose down || true
                '''
            }
        }
        stage('Run Containers') {
            steps {
                sh 'docker-compose up -d --build'
            }
        }
    }
}
